import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import MSWWrapper from '@/components/MSWWrapper';
import QueryProvider from '@/components/QueryProvider';
import { initMsw } from '@/mocks';

initMsw();

const kiaFont = localFont({
  src: [
    {
      path: '../fonts/KiaSignatureFixRegular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/KiaSignatureFixBold.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-kia', // Tailwind에서 사용하기 위한 CSS 변수 설정
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kiaFont.variable} font-kia`}>
        <MSWWrapper>
          <QueryProvider>{children}</QueryProvider>
        </MSWWrapper>
      </body>
    </html>
  );
}
